#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("See4Me.Android.Resource", IsApplication=true)]

namespace See4Me.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::GalaSoft.MvvmLight.Resource.String.ApplicationName = global::See4Me.Android.Resource.String.ApplicationName;
			global::GalaSoft.MvvmLight.Resource.String.Hello = global::See4Me.Android.Resource.String.Hello;
			global::Plugin.TextToSpeech.Resource.String.ApplicationName = global::See4Me.Android.Resource.String.ApplicationName;
			global::Plugin.TextToSpeech.Resource.String.Hello = global::See4Me.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int splash_screen = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int textViewMessage = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int textureViewMain = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int AppName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int BackCameraReady = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int FrontCameraReady = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int InitializationError = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int NoConnection = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int QueryingVisionService = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int RecognitionError = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int RecognitionFailed = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int ResourceLanguage = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int Translating = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int UnableToGetImage = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int VisionServiceQueried = 2130968589;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int See4Me = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int See4Me_Splash = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
