//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace See4Me.Localization.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("See4Me.Localization.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angry.
        /// </summary>
        public static string AngerFemale {
            get {
                return ResourceManager.GetString("AngerFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angry.
        /// </summary>
        public static string AngerMale {
            get {
                return ResourceManager.GetString("AngerMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See4Me.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back camera ready.
        /// </summary>
        public static string BackCameraReady {
            get {
                return ResourceManager.GetString("BackCameraReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girl.
        /// </summary>
        public static string BoyFemale {
            get {
                return ResourceManager.GetString("BoyFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boy.
        /// </summary>
        public static string BoyMale {
            get {
                return ResourceManager.GetString("BoyMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        public static string ChildFemale {
            get {
                return ResourceManager.GetString("ChildFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        public static string ChildMale {
            get {
                return ResourceManager.GetString("ChildMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To show contempt.
        /// </summary>
        public static string ContemptFemale {
            get {
                return ResourceManager.GetString("ContemptFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To show contempt.
        /// </summary>
        public static string ContemptMale {
            get {
                return ResourceManager.GetString("ContemptMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disgusted.
        /// </summary>
        public static string DisgustFemale {
            get {
                return ResourceManager.GetString("DisgustFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disgusted.
        /// </summary>
        public static string DisgustMale {
            get {
                return ResourceManager.GetString("DisgustMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I see a person.
        /// </summary>
        public static string FaceRecognizedSingular {
            get {
                return ResourceManager.GetString("FaceRecognizedSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I see {0} people.
        /// </summary>
        public static string FacesRecognizedPlural {
            get {
                return ResourceManager.GetString("FacesRecognizedPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fearful.
        /// </summary>
        public static string FearFemale {
            get {
                return ResourceManager.GetString("FearFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fearful.
        /// </summary>
        public static string FearMale {
            get {
                return ResourceManager.GetString("FearMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front camera ready.
        /// </summary>
        public static string FrontCameraReady {
            get {
                return ResourceManager.GetString("FrontCameraReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy.
        /// </summary>
        public static string HappinessFemale {
            get {
                return ResourceManager.GetString("HappinessFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy.
        /// </summary>
        public static string HappinessMale {
            get {
                return ResourceManager.GetString("HappinessMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during app initialization.
        /// </summary>
        public static string InitializationError {
            get {
                return ResourceManager.GetString("InitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to looking {0}.
        /// </summary>
        public static string LookingFemale {
            get {
                return ResourceManager.GetString("LookingFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to looking {0}.
        /// </summary>
        public static string LookingMale {
            get {
                return ResourceManager.GetString("LookingMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woman.
        /// </summary>
        public static string ManFemale {
            get {
                return ResourceManager.GetString("ManFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Man.
        /// </summary>
        public static string ManMale {
            get {
                return ResourceManager.GetString("ManMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        public static string NeutralFemale {
            get {
                return ResourceManager.GetString("NeutralFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        public static string NeutralMale {
            get {
                return ResourceManager.GetString("NeutralMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, Internet is not available.
        /// </summary>
        public static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} years old {1}.
        /// </summary>
        public static string PersonAgeMessageFemale {
            get {
                return ResourceManager.GetString("PersonAgeMessageFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} years old {1}.
        /// </summary>
        public static string PersonAgeMessageMale {
            get {
                return ResourceManager.GetString("PersonAgeMessageMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing the image....
        /// </summary>
        public static string QueryingVisionService {
            get {
                return ResourceManager.GetString("QueryingVisionService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, there was un unexpected error.
        /// </summary>
        public static string RecognitionError {
            get {
                return ResourceManager.GetString("RecognitionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, I don&apos;t recognize the image.
        /// </summary>
        public static string RecognitionFailed {
            get {
                return ResourceManager.GetString("RecognitionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sad.
        /// </summary>
        public static string SadnessFemale {
            get {
                return ResourceManager.GetString("SadnessFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sad.
        /// </summary>
        public static string SadnessMale {
            get {
                return ResourceManager.GetString("SadnessMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surprised.
        /// </summary>
        public static string SurpriseFemale {
            get {
                return ResourceManager.GetString("SurpriseFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surprised.
        /// </summary>
        public static string SurpriseMale {
            get {
                return ResourceManager.GetString("SurpriseMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translating....
        /// </summary>
        public static string Translating {
            get {
                return ResourceManager.GetString("Translating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, I can&apos;t get the image.
        /// </summary>
        public static string UnableToGetImage {
            get {
                return ResourceManager.GetString("UnableToGetImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imaged successfully analyzed.
        /// </summary>
        public static string VisionServiceQueried {
            get {
                return ResourceManager.GetString("VisionServiceQueried", resourceCulture);
            }
        }
    }
}
