//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace See4Me.Localization.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("See4Me.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        public static string AboutCommand {
            get {
                return ResourceManager.GetString("AboutCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by Marco Minerva - MVP Windows Development.
        /// </summary>
        public static string AndroidProjectAuthor {
            get {
                return ResourceManager.GetString("AndroidProjectAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angry.
        /// </summary>
        public static string AngerFemale {
            get {
                return ResourceManager.GetString("AngerFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angry.
        /// </summary>
        public static string AngerMale {
            get {
                return ResourceManager.GetString("AngerMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See4Me.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See4Me.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back camera ready.
        /// </summary>
        public static string BackCameraReady {
            get {
                return ResourceManager.GetString("BackCameraReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog:.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girl.
        /// </summary>
        public static string BoyFemale {
            get {
                return ResourceManager.GetString("BoyFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boy.
        /// </summary>
        public static string BoyMale {
            get {
                return ResourceManager.GetString("BoyMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        public static string ChildFemale {
            get {
                return ResourceManager.GetString("ChildFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        public static string ChildMale {
            get {
                return ResourceManager.GetString("ChildMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have the consent of the people whose data (such as images, voices, video or text) are being processed by See4Me. Consent is required to use the app. See4Me adheres to all applicable privacy regulations. By proceding, you confirm you have the consent..
        /// </summary>
        public static string ConsentRequiredMessage {
            get {
                return ResourceManager.GetString("ConsentRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consent required.
        /// </summary>
        public static string ConsentRequiredTitle {
            get {
                return ResourceManager.GetString("ConsentRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To show contempt.
        /// </summary>
        public static string ContemptFemale {
            get {
                return ResourceManager.GetString("ContemptFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To show contempt.
        /// </summary>
        public static string ContemptMale {
            get {
                return ResourceManager.GetString("ContemptMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disgusted.
        /// </summary>
        public static string DisgustFemale {
            get {
                return ResourceManager.GetString("DisgustFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disgusted.
        /// </summary>
        public static string DisgustMale {
            get {
                return ResourceManager.GetString("DisgustMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emotion Subscription Key.
        /// </summary>
        public static string EmotionSubscriptionKey {
            get {
                return ResourceManager.GetString("EmotionSubscriptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I see.
        /// </summary>
        public static string FaceRecognizedSingular {
            get {
                return ResourceManager.GetString("FaceRecognizedSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I see {0} people.
        /// </summary>
        public static string FacesRecognizedPlural {
            get {
                return ResourceManager.GetString("FacesRecognizedPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Subscription Key.
        /// </summary>
        public static string FaceSubscriptionKey {
            get {
                return ResourceManager.GetString("FaceSubscriptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fearful.
        /// </summary>
        public static string FearFemale {
            get {
                return ResourceManager.GetString("FearFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fearful.
        /// </summary>
        public static string FearMale {
            get {
                return ResourceManager.GetString("FearMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front camera ready.
        /// </summary>
        public static string FrontCameraReady {
            get {
                return ResourceManager.GetString("FrontCameraReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Cognitive Services Home Page.
        /// </summary>
        public static string GotoCognitiveServices {
            get {
                return ResourceManager.GetString("GotoCognitiveServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow the project on GitHub.
        /// </summary>
        public static string GotoGitHub {
            get {
                return ResourceManager.GetString("GotoGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy.
        /// </summary>
        public static string HappinessFemale {
            get {
                return ResourceManager.GetString("HappinessFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy.
        /// </summary>
        public static string HappinessMale {
            get {
                return ResourceManager.GetString("HappinessMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during app initialization.
        /// </summary>
        public static string InitializationError {
            get {
                return ResourceManager.GetString("InitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by Riccardo Cappello.
        /// </summary>
        public static string iOSProjectAuthor {
            get {
                return ResourceManager.GetString("iOSProjectAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkedin:.
        /// </summary>
        public static string LinkedIn {
            get {
                return ResourceManager.GetString("LinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to looking {0}.
        /// </summary>
        public static string LookingFemale {
            get {
                return ResourceManager.GetString("LookingFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to looking {0}.
        /// </summary>
        public static string LookingMale {
            get {
                return ResourceManager.GetString("LookingMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woman.
        /// </summary>
        public static string ManFemale {
            get {
                return ResourceManager.GetString("ManFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Man.
        /// </summary>
        public static string ManMale {
            get {
                return ResourceManager.GetString("ManMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft privacy policies.
        /// </summary>
        public static string MicrosoftPrivacyPolicies {
            get {
                return ResourceManager.GetString("MicrosoftPrivacyPolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        public static string NeutralFemale {
            get {
                return ResourceManager.GetString("NeutralFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        public static string NeutralMale {
            get {
                return ResourceManager.GetString("NeutralMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, there is no Internet connection.
        /// </summary>
        public static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Settings.
        /// </summary>
        public static string OpenSettings {
            get {
                return ResourceManager.GetString("OpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {1} years old {0}.
        /// </summary>
        public static string PersonAgeMessageFemale {
            get {
                return ResourceManager.GetString("PersonAgeMessageFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {1} years old {0}.
        /// </summary>
        public static string PersonAgeMessageMale {
            get {
                return ResourceManager.GetString("PersonAgeMessageMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by Microsoft’s Cognitive Services:.
        /// </summary>
        public static string PoweredByCognitiveServices {
            get {
                return ResourceManager.GetString("PoweredByCognitiveServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy....
        /// </summary>
        public static string PrivacyPolicyCommand {
            get {
                return ResourceManager.GetString("PrivacyPolicyCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image, voice, video or text understanding capabilities of See4Me app uses Microsoft Cognitive Services. Microsoft will receive the images, audio, video, and other data that you upload (via this app) for service improvement purposes. To report abuse of the Microsoft Cognitive Services to Microsoft, please visit the Microsoft Cognitive Services website at https://www.microsoft.com/cognitive-services, and use the &quot;Report Abuse&quot; link at the bottom of the page to contact Microsoft. For more information about [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PrivacyStatement {
            get {
                return ResourceManager.GetString("PrivacyStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing the image....
        /// </summary>
        public static string QueryingVisionService {
            get {
                return ResourceManager.GetString("QueryingVisionService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, there was an unexpected error.
        /// </summary>
        public static string RecognitionError {
            get {
                return ResourceManager.GetString("RecognitionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, I don&apos;t recognize the image.
        /// </summary>
        public static string RecognitionFailed {
            get {
                return ResourceManager.GetString("RecognitionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognize Text.
        /// </summary>
        public static string RecognizeText {
            get {
                return ResourceManager.GetString("RecognizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognizing faces and emotions....
        /// </summary>
        public static string RecognizingFaces {
            get {
                return ResourceManager.GetString("RecognizingFaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognizing text....
        /// </summary>
        public static string RecognizingText {
            get {
                return ResourceManager.GetString("RecognizingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sad.
        /// </summary>
        public static string SadnessFemale {
            get {
                return ResourceManager.GetString("SadnessFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sad.
        /// </summary>
        public static string SadnessMale {
            get {
                return ResourceManager.GetString("SadnessMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention, the service is not registered. Go to Settings page to enter the required keys..
        /// </summary>
        public static string ServiceNotRegistered {
            get {
                return ResourceManager.GetString("ServiceNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show description confidence.
        /// </summary>
        public static string ShowDescriptionConfidence {
            get {
                return ResourceManager.GetString("ShowDescriptionConfidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show original description on translation.
        /// </summary>
        public static string ShowOriginalDescriptionOnTranslation {
            get {
                return ResourceManager.GetString("ShowOriginalDescriptionOnTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to get the key.
        /// </summary>
        public static string SubscribeCognitiveServices {
            get {
                return ResourceManager.GetString("SubscribeCognitiveServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to get the key.
        /// </summary>
        public static string SubscribeTranslatorService {
            get {
                return ResourceManager.GetString("SubscribeTranslatorService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surprised.
        /// </summary>
        public static string SurpriseFemale {
            get {
                return ResourceManager.GetString("SurpriseFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surprised.
        /// </summary>
        public static string SurpriseMale {
            get {
                return ResourceManager.GetString("SurpriseMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap camera.
        /// </summary>
        public static string SwapCamera {
            get {
                return ResourceManager.GetString("SwapCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, I&apos;m unable to swap camera.
        /// </summary>
        public static string SwapCameraError {
            get {
                return ResourceManager.GetString("SwapCameraError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a photo.
        /// </summary>
        public static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text-To-Speech.
        /// </summary>
        public static string TextToSpeech {
            get {
                return ResourceManager.GetString("TextToSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translating....
        /// </summary>
        public static string Translating {
            get {
                return ResourceManager.GetString("Translating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translator Subscription Key.
        /// </summary>
        public static string TranslatorSubscriptionKey {
            get {
                return ResourceManager.GetString("TranslatorSubscriptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter:.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to access the service. Ensure that registration keys are correct.
        /// </summary>
        public static string UnableToAccessService {
            get {
                return ResourceManager.GetString("UnableToAccessService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, I can&apos;t recognize text inside the photo.
        /// </summary>
        public static string UnableToRecognizeText {
            get {
                return ResourceManager.GetString("UnableToRecognizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, I can&apos;t take the photo. Try restarting the app.
        /// </summary>
        public static string UnableToTakePhoto {
            get {
                return ResourceManager.GetString("UnableToTakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision Subscription Key.
        /// </summary>
        public static string VisionSubscriptionKey {
            get {
                return ResourceManager.GetString("VisionSubscriptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by Marco Minerva - MVP Windows Development.
        /// </summary>
        public static string WindowsProjectAuthor {
            get {
                return ResourceManager.GetString("WindowsProjectAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
