#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("See4Me.Resource", IsApplication=true)]

namespace See4Me
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Plugin.TextToSpeech.Resource.String.ApplicationName = global::See4Me.Resource.String.ApplicationName;
			global::Plugin.TextToSpeech.Resource.String.Hello = global::See4Me.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int camera = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int roundedbutton = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int splash_screen = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int takePhotoButton = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int textViewMessage = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int textureViewMain = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int About = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int AboutCommand = 2130968579;
			
			// aapt resource value: 0x7f04004e
			public const int AndroidProjectAuthor = 2130968654;
			
			// aapt resource value: 0x7f040004
			public const int AngerFemale = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int AngerMale = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int AppName = 2130968583;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int ApplicationTitle = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int BackCameraReady = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int Blog = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int BoyFemale = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int BoyMale = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int ChildFemale = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int ChildMale = 2130968589;
			
			// aapt resource value: 0x7f040046
			public const int ConsentRequiredMessage = 2130968646;
			
			// aapt resource value: 0x7f040047
			public const int ConsentRequiredTitle = 2130968647;
			
			// aapt resource value: 0x7f04000e
			public const int ContemptFemale = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int ContemptMale = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int DisgustFemale = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int DisgustMale = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int EmotionSubscriptionKey = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int FaceRecognizedSingular = 2130968595;
			
			// aapt resource value: 0x7f040051
			public const int FaceSubscriptionKey = 2130968657;
			
			// aapt resource value: 0x7f040014
			public const int FacesRecognizedPlural = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int FearFemale = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int FearMale = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int FrontCameraReady = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int GotoCognitiveServices = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int GotoGitHub = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int HappinessFemale = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int HappinessMale = 2130968603;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f04001c
			public const int InitializationError = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int LinkedIn = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int LookingFemale = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int LookingMale = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int ManFemale = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int ManMale = 2130968609;
			
			// aapt resource value: 0x7f04004b
			public const int MicrosoftPrivacyPolicies = 2130968651;
			
			// aapt resource value: 0x7f040022
			public const int NeutralFemale = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int NeutralMale = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int No = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int NoConnection = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int OK = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int OpenSettings = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int PersonAgeMessageFemale = 2130968616;
			
			// aapt resource value: 0x7f040029
			public const int PersonAgeMessageMale = 2130968617;
			
			// aapt resource value: 0x7f04004c
			public const int PoweredByCognitiveServices = 2130968652;
			
			// aapt resource value: 0x7f040048
			public const int PrivacyPolicy = 2130968648;
			
			// aapt resource value: 0x7f040049
			public const int PrivacyPolicyCommand = 2130968649;
			
			// aapt resource value: 0x7f04004a
			public const int PrivacyStatement = 2130968650;
			
			// aapt resource value: 0x7f04002b
			public const int QueryingVisionService = 2130968619;
			
			// aapt resource value: 0x7f04002c
			public const int RecognitionError = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int RecognitionFailed = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int RecognizeText = 2130968622;
			
			// aapt resource value: 0x7f040054
			public const int RecognizingEmotions = 2130968660;
			
			// aapt resource value: 0x7f04002f
			public const int RecognizingFaces = 2130968623;
			
			// aapt resource value: 0x7f04004d
			public const int RecognizingText = 2130968653;
			
			// aapt resource value: 0x7f040050
			public const int RegisterServices = 2130968656;
			
			// aapt resource value: 0x7f040030
			public const int ResourceLanguage = 2130968624;
			
			// aapt resource value: 0x7f040031
			public const int SadnessFemale = 2130968625;
			
			// aapt resource value: 0x7f040032
			public const int SadnessMale = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int Save = 2130968627;
			
			// aapt resource value: 0x7f040034
			public const int ServiceNotRegistered = 2130968628;
			
			// aapt resource value: 0x7f040035
			public const int Settings = 2130968629;
			
			// aapt resource value: 0x7f040036
			public const int ShowDescriptionConfidence = 2130968630;
			
			// aapt resource value: 0x7f040053
			public const int ShowDescriptionOnFaceIdentification = 2130968659;
			
			// aapt resource value: 0x7f040037
			public const int ShowOriginalDescriptionOnTranslation = 2130968631;
			
			// aapt resource value: 0x7f040052
			public const int ShuttingDown = 2130968658;
			
			// aapt resource value: 0x7f040038
			public const int SurpriseFemale = 2130968632;
			
			// aapt resource value: 0x7f040039
			public const int SurpriseMale = 2130968633;
			
			// aapt resource value: 0x7f04003a
			public const int SwapCamera = 2130968634;
			
			// aapt resource value: 0x7f04003b
			public const int SwapCameraError = 2130968635;
			
			// aapt resource value: 0x7f04003c
			public const int TakePhoto = 2130968636;
			
			// aapt resource value: 0x7f04003d
			public const int TextToSpeech = 2130968637;
			
			// aapt resource value: 0x7f04003e
			public const int Translating = 2130968638;
			
			// aapt resource value: 0x7f04003f
			public const int TranslatorSubscriptionKey = 2130968639;
			
			// aapt resource value: 0x7f040040
			public const int Twitter = 2130968640;
			
			// aapt resource value: 0x7f040041
			public const int UnableToAccessService = 2130968641;
			
			// aapt resource value: 0x7f040042
			public const int UnableToRecognizeText = 2130968642;
			
			// aapt resource value: 0x7f040043
			public const int UnableToTakePhoto = 2130968643;
			
			// aapt resource value: 0x7f040044
			public const int VisionSubscriptionKey = 2130968644;
			
			// aapt resource value: 0x7f04002a
			public const int WindowsProjectAuthor = 2130968618;
			
			// aapt resource value: 0x7f040045
			public const int Yes = 2130968645;
			
			// aapt resource value: 0x7f04004f
			public const int iOSProjectAuthor = 2130968655;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int See4Me = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int See4Me_Splash = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
